# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NBA.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 463)
        MainWindow.setStyleSheet("background-image:url(\"D:888.jpg\")")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 461, 51))
        font = QtGui.QFont()
        font.setFamily("華康雅宋體")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 121, 41))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 61, 31))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 70, 341, 41))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:transparent;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(580, 70, 111, 41))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.player_label = QtWidgets.QLabel(self.centralwidget)
        self.player_label.setGeometry(QtCore.QRect(90, 150, 271, 321))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(20)
        self.player_label.setFont(font)
        self.player_label.setStyleSheet("background:transparent;\n"
"color:rgb(200, 109, 18)")
        self.player_label.setText("")
        self.player_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.player_label.setObjectName("player_label")
        self.history_label = QtWidgets.QLabel(self.centralwidget)
        self.history_label.setGeometry(QtCore.QRect(360, 150, 271, 321))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(20)
        self.history_label.setFont(font)
        self.history_label.setStyleSheet("background:transparent;\n"
"color:rgb(200, 109, 18)\n"
"")
        self.history_label.setText("")
        self.history_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.history_label.setObjectName("history_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 739, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "NBA球員點將錄(2021-2022)"))
        self.label_2.setText(_translate("MainWindow", "查詢球員:"))
        self.pushButton.setText(_translate("MainWindow", "查詢"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
