# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1188, 600)
        MainWindow.setStyleSheet("background-image:url(\"D:666.jpg\")")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Data_Analysis_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Data_Analysis_btn.setGeometry(QtCore.QRect(550, 140, 241, 71))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(16)
        self.Data_Analysis_btn.setFont(font)
        self.Data_Analysis_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Data_Analysis_btn.setStyleSheet("color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"background-color:rgb(85, 170, 255)")
        self.Data_Analysis_btn.setObjectName("Data_Analysis_btn")
        self.Web_Crawler_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Web_Crawler_btn.setGeometry(QtCore.QRect(550, 310, 241, 71))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(16)
        self.Web_Crawler_btn.setFont(font)
        self.Web_Crawler_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Web_Crawler_btn.setStyleSheet("color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"background-color:rgb(85, 170, 255)")
        self.Web_Crawler_btn.setObjectName("Web_Crawler_btn")
        self.Computer_Vision_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Computer_Vision_btn.setGeometry(QtCore.QRect(550, 450, 241, 71))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(16)
        self.Computer_Vision_btn.setFont(font)
        self.Computer_Vision_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Computer_Vision_btn.setStyleSheet("color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"background-color:rgb(85, 170, 255)")
        self.Computer_Vision_btn.setObjectName("Computer_Vision_btn")
        self.webcam_detect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.webcam_detect_btn.setGeometry(QtCore.QRect(860, 450, 241, 71))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(16)
        self.webcam_detect_btn.setFont(font)
        self.webcam_detect_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.webcam_detect_btn.setStyleSheet("color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"background-color:rgb(85, 170, 255)")
        self.webcam_detect_btn.setObjectName("webcam_detect_btn")
        self.Title_label = QtWidgets.QLabel(self.centralwidget)
        self.Title_label.setGeometry(QtCore.QRect(250, -20, 871, 91))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(48)
        self.Title_label.setFont(font)
        self.Title_label.setStyleSheet("background:transparent;\n"
"color:rgb(255, 255, 255);")
        self.Title_label.setObjectName("Title_label")
        self.QRcode_label = QtWidgets.QLabel(self.centralwidget)
        self.QRcode_label.setGeometry(QtCore.QRect(870, 70, 221, 211))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(7)
        self.QRcode_label.setFont(font)
        self.QRcode_label.setStyleSheet("background-image:url(\"D:777.png\")\n"
"")
        self.QRcode_label.setText("")
        self.QRcode_label.setTextFormat(QtCore.Qt.AutoText)
        self.QRcode_label.setObjectName("QRcode_label")
        self.myself_label = QtWidgets.QLabel(self.centralwidget)
        self.myself_label.setGeometry(QtCore.QRect(920, 530, 261, 31))
        self.myself_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"font: 16pt \"a song for jennifer bold\";\n"
"")
        self.myself_label.setObjectName("myself_label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 0, 421, 551))
        self.frame.setStyleSheet("background:transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(20, 80, 431, 421))
        self.tableWidget.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-width:1px;\n"
"border-style:outset;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("background:transparent;\n"
"color:rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(174, 512, 81, 31))
        self.pushButton.setStyleSheet("background:transparent;\n"
"color:rgb(255, 255, 255);\n"
"border-width:1px;\n"
"border-style:outset;")
        self.pushButton.setObjectName("pushButton")
        self.yolo_btn = QtWidgets.QPushButton(self.centralwidget)
        self.yolo_btn.setGeometry(QtCore.QRect(860, 310, 241, 71))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(16)
        self.yolo_btn.setFont(font)
        self.yolo_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.yolo_btn.setStyleSheet("color:white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"background-color:rgb(85, 170, 255)")
        self.yolo_btn.setObjectName("yolo_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1188, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Data_Analysis_btn.setText(_translate("MainWindow", "Data Analysis"))
        self.Web_Crawler_btn.setText(_translate("MainWindow", "Web Crawler"))
        self.Computer_Vision_btn.setText(_translate("MainWindow", "Computer Vision"))
        self.webcam_detect_btn.setText(_translate("MainWindow", "webcam detect"))
        self.Title_label.setText(_translate("MainWindow", "                Computer Information"))
        self.myself_label.setText(_translate("MainWindow", "By Tzu-Hao Weng 2022/01/15"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "帳號"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "信箱"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "密碼"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "確認密碼"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "checkint"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "隨機碼"))
        self.label.setText(_translate("MainWindow", "子浩系統會員名單"))
        self.pushButton.setText(_translate("MainWindow", "開啟名單"))
        self.yolo_btn.setText(_translate("MainWindow", "Yolo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
