# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(352, 464)
        MainWindow.setStyleSheet("background-color:rgb(235, 235, 235)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 201, 201))
        self.label.setStyleSheet("background-image:url(\"D:999.png\")")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 250, 71, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 300, 71, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.account_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.account_lineEdit.setGeometry(QtCore.QRect(110, 250, 191, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.account_lineEdit.setFont(font)
        self.account_lineEdit.setObjectName("account_lineEdit")
        self.secret_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.secret_lineEdit.setGeometry(QtCore.QRect(110, 300, 191, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.secret_lineEdit.setFont(font)
        self.secret_lineEdit.setObjectName("secret_lineEdit")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(70, 360, 91, 41))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(16)
        self.login_btn.setFont(font)
        self.login_btn.setObjectName("login_btn")
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setGeometry(QtCore.QRect(190, 360, 91, 41))
        font = QtGui.QFont()
        font.setFamily("a song for jennifer bold")
        font.setPointSize(16)
        self.create_btn.setFont(font)
        self.create_btn.setObjectName("create_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 352, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "帳號:"))
        self.label_3.setText(_translate("MainWindow", "密碼:"))
        self.login_btn.setText(_translate("MainWindow", "登入"))
        self.create_btn.setText(_translate("MainWindow", "註冊"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
